### PR TITLE
rework page preview to use transformers. page frame now uses placeholders

### PR DESCRIPTION
**Pull request by ylebre**

### CODE REVIEW

**Comment by poef** [comment]
Ik zie dat de placeholders formaat '{placeholder}' hebben. Moustache gebruikt '{{placeholder}}', en javascript templated strings gebruiken '${placeholder}'. Ik zou liever een van die 2 zien, in de rest van de code vallen ze meer op.

**Comment by ylebre** [comment]
I've opted to use {{ }}. The syntax for javascript templated strings might raise the expectation of the placeholders being able to do more than just be a simple placeholder to be replaced.

**Comment by poef** [comment]
> I've opted to use {{ }}. The syntax for javascript templated strings might raise the expectation of the placeholders being able to do more than just be a simple placeholder to be replaced.

Is there a reason to match (\s+){{...}} instead of just {{...}} ? It feels a bit arbitrary.

**Comment by ylebre** [comment]
Yes - it will take the space-symbols from the start of the line to do indenting with, so the generated code will be indented properly as well.

**Pull request merged**
